### ISSUE TITLE
[Announcement] FDM Monster is a FOSS replacement for OctoFarm

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#1678]
Hi all,

I wanted to make clear that this project is **not** going closed source, or in other words this project FDM Monster is more alive than ever. The version that did go closed source has completely spun off.

**The reason for a spinoff**
The spinoff version allowed me to fully detach the codebase from this open source AGPLv3 version.
It carries a complete redesign of the server from the ground up for the requests/demands of a quite specific farm. I will reapply those lessons/prototypes to FDM Monster in the future. But, instead of triaging the features towards 1 farm type, the FDM Monster redesign will be much better suited for use in 3D Printing farms with wide-ranging feature requests.

**Why should you choose FDM Monster**
You might be aware that OctoFarm has stalled in development completely. The server is dealing with quite some issues in the stable release. And, although there is or might be a new owner soon, they will not be picking up the pace in quite some time due to the size of the project and the amount of code to refactor. 

This is exactly where FDM Monster comes in: 
- it is without legacy problems
- it helps with the complex workflow of commercial (large) 3D Print farms
- unnecessary features are fended off with careful triage and consideration
- yet, new plans are developing rapidly 
- the codebase is tweaked, stable and battle-tested for large farms over 1.5 years

**Comment by Dumnersm580** [comment]
# FDM Monster

Welcome to the documentation page for FDM Monster - a 3D printing farm management software designed for commercial use. In this page, we will cover the reasons behind the spinoff of the closed-source version, as well as the advantages of using FDM Monster over other similar software in the market.

## Project Status

Firstly, we would like to make it clear that FDM Monster is not going closed source. The version that did go closed source has completely spun off, and the FDM Monster project is more alive than ever. 

The reason for the spinoff was to allow us to fully detach the codebase from the open source AGPLv3 version. The spinoff version carries a complete redesign of the server from the ground up for the requests and demands of a specific farm. We will reapply those lessons and prototypes to FDM Monster in the future. However, instead of triaging the features towards one farm type, the FDM Monster redesign will be much better suited for use in 3D printing farms with wide-ranging feature requests.

## Why Choose FDM Monster?

If you're considering using FDM Monster for your 3D printing farm management needs, here are a few reasons why it might be the best choice for you:

- **No legacy problems:** FDM Monster is designed from the ground up, which means it doesn't have any legacy problems that come with using older software.

- **Complex workflow:** FDM Monster is specifically designed to help with the complex workflow of commercial 3D printing farms. This means it can handle a high volume of orders and can be customized to fit your specific needs.

- **Careful feature selection:** Unnecessary features are fended off with careful triage and consideration. This means that FDM Monster only includes features that are necessary for the efficient management of 3D printing farms.

- **New plans:** Despite its stable and battle-tested codebase, FDM Monster is always evolving. We are constantly working on new plans to improve the software and make it even better suited for commercial use.

- **Battle-tested:** The codebase of FDM Monster has been tweaked, stabilized and battle-tested for large farms over 1.5 years. This means you can trust that it will work reliably and efficiently for your 3D printing farm.

Thank you for considering FDM Monster for your 3D printing farm management needs. If you have any further questions or would like more information, please don't hesitate to contact us.
