### ISSUE TITLE
When creating a printer, nothing appears in "Checks" when test connection is clicked

### ISSUE THREAD

**Issue by MKELEE2024** [fdm-monster/fdm-monster#2926]
**Describe the bug**
Trying to create a printer using the printer URL and API keys, nothing happens when clicking test connection, nothing appears in "Checks".

**To Reproduce**
Create a printer, fill out URL and API click test connection
>
> 
**Expected behavior**
>I expect something to happen when clicking test connection.  Nothing appears in "Checks"

**Screenshots**
>
![test_connection](https://github.com/fdm-monster/fdm-monster/assets/160533306/b42daec3-950e-43bc-9188-1b9fcf116ded)

**Browser (please complete the following information):**
 - OS: [FDM Pi image, Octoprint Pi image, all updates have been run]
 - Browser [chrome]
 - 

**Additional context**
I don't have a line to enter the port number.  When I click "test connection" nothing happens

**Comment by davidzwa** [comment]
Hi, thanks for the bug report. Your problem is (most likely) due to not adding the port to the URL itself.

> I don't have a line to enter the port number.

The port is to be included in the URL. For example, port 7000 would result in such a URL: `http://localhost:7000`.
Let me give more examples:
- `http://octopi.local:5000`
- `http://192.168.1.100:3000`
- `http://192.168.1.100` (port 80 is implied due to http default)
- `https://192.168.1.100` (port 443 is implied due to https default)

## Further points:
- It is unclear which server / client versions you are reporting this for. Try to check the about page, question mark on the left side navigation (path: /about)
- I have improved the connection panel problem being empty. This will be available in server version 1.6.1 to be released soon. It is available on the `develop` branch of github, which is not available for MonsterPi yet.
- I have tackled the fact that the panel incorrectly colors certain statuses. This is less relevant for you, but still related.
