### ISSUE TITLE
When opening printer file explorer sidenav 500 exception is thrown when saving file to db

### ISSUE THREAD

**Issue by shandshellin** [fdm-monster/fdm-monster#3169]
I can create the printers and add cameras but no controls and if i view details i keep getting error 500. 

AN ERROR OCCURRED
Request failed with status code 500 - URL /api/printer-files/1/?recursive=false

Here are the logs

[fdm-monster-2024-04-26.log](https://github.com/fdm-monster/fdm-monster/files/15134669/fdm-monster-2024-04-26.log)
[pm2.error.log](https://github.com/fdm-monster/fdm-monster/files/15134670/pm2.error.log)
[pm2.log](https://github.com/fdm-monster/fdm-monster/files/15134671/pm2.log)

**Comment by davidzwa** [comment]
I do see in your logs that you are getting errors while files are being stored to database. This action is called when the side panel is opened.
One other error I see is "self signed certificate". Please check if this is a problem as well.

In order to help you better I need details that the log will not show. Therefore, could you enable diagnostics?
https://docs.fdm-monster.net/docs/troubleshooting#sentry

**Comment by shandshellin** [comment]
.log files are added to the first post, do you not see them?

**Comment by shandshellin** [comment]
sentry enabled

**Comment by davidzwa** [comment]
I received the error in Sentry. Its ok to disable diagnostics again.

**Comment by davidzwa** [comment]
QueryFailedError: SqliteError: NOT NULL constraint failed: printer_file.hash

I will this asap.

**Comment by shandshellin** [comment]
I can see the files now, thanks. The issue now is the printer controls. If i refresh the page i can open the controls once for one printer and then they are just blank, then refresh the page and i can open one of the controls. Thoughts?

**Comment by shandshellin** [comment]
i enabled diag again.
